name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-pipeline-templates    

variables:
  projectDirPath: 'App'
  awsAccountId: '111111111111'

extends:
  template: kaniko/build-docker-image-via-kaniko-job.yml@templates
  parameters:            
    dockerRegistry: '111111111111.dkr.ecr.eu-west-1.amazonaws.com'
    clusterSecretName: 'eks-azdo-agents'